### PR TITLE
Make elan more permissive with names of linked toolchains

### PR DESCRIPTION
**Pull request by cipher1024**

### CODE REVIEW

**Comment by Kha** [comment]
It looks like I made a mistake when simplifying the rustup source here - [it should return `self.is_custom()`](https://github.com/rust-lang/rustup.rs/commit/86ef1571fbef4d18e1cdcd61ea48b0e5e7fa3531) for `Link` and `Copy` (`Copy` ultimately is dead code btw in elan). We don't want users to accidentally link `nightly` to a local version.

**Comment by cipher1024** [comment]
Oh, that makes sense! I'll make the change.

There's another thing too though. Is the assertion the first time the name gets checked? Maybe it should be checked earlier to give a proper error message.

**Comment by gebner** [comment]
Is there anything left to do before we can merge this PR?

**Comment by Kha** [comment]
Notifying me that the PR was updated :>

**Pull request merged**
